### PR TITLE
bug/215-terms-and-conditions

### PR DESCRIPTION
**Pull request by yus252**

### CODE REVIEW

**Comment by yxlin118** [comment]
Maybe change to such that that warning only shows up if the user clicked on the signin or guest option without checking the checkbox(similar to the signin page warning)

**Comment by yus252** [comment]
> Maybe change to such that that warning only shows up if the user clicked on the signin or guest option without checking the checkbox(similar to the signin page warning)

fixed

**Comment by yxlin118** [comment]
Is it possible to make red and not italicized? Maybe not the italicization part but I think for sure red is better.

**Comment by yus252** [comment]
> Is it possible to make red and not italicized? Maybe not the italicization part but I think for sure red is better.

Deleted <em> and changed the warning into red.

**Comment by yxlin118** [comment]
Looks good! One small thing, the icon is not aligned with the text.

**Pull request merged**
