### PR TITLE
Feature/108 change status

### PR DESCRIPTION
**Pull request by yxlin118**
Added a SickCheck and TestCheck page that's similar to Onboard and Confirm respectively to allow daily assessment to update sick and test status without going to the critical questions page and only go to symptoms page if sick is selected.

### CODE REVIEW

**Comment by yxlin118** [comment]
@pyritewolf I wanted to skip the critical questions page and I am not sure how to configure the original onboard->confirm->questions page such that it can have three possible path: 1) go to dashboard after confirm 2) go to symptoms after confirm 3) go to questions after confirm. Do you have any advice on how to do that? Thanks!

**Comment by pyritewolf** [comment]
The easiest way I can think of is using React Router's `<Link>` (instead of MUI's) and sending an [object path](https://reactrouter.com/web/api/Link/to-object) with a `state` property. The router state is a piece of information passed from one view to another during the navigation process. In that state, we could have a `flow` key that knows what flow are we following (be it the onboarding or the daily check), and the flow can know what's the next step for each screen. At its heart, it's a state machine!

How could all of this be practically applied to the code? Here's a loose example that probably has a lot of syntax errors 😅 

**paths.js**
```javascript
export const ONBOARDING_FLOW = {
   // this constant could have a key for each possible path and where do they lead
   // here's one as an example!
   paths.confirm: {
      next: paths.questions,
      prev: paths.onboard,
   },
  // ... the rest of the regular flow
};

export const DAILY_CHECK_FLOW = {
   // this would be the same as the one before
   // but with the next/prev values changed for the daily check's necessities
   paths.confirm: {
      next: paths.symptoms,
      prev: paths.onboard,
   },
  // ... the rest of the special flow
};

// this is a little helper method that I think could be handy
// something similar could be done for the prevPath case
export const getNextPath = (currentPath, location) => {
   // return the default if there's no state
   if (!(location.state && location.state.flow)) return ONBOARDING_FLOW[currentPath].next;
   // otherwise, return the current flow's next path
   return location.state.flow[currentPath].next;
}
```

**on the dashboard view**
```javascript
import Link from 'react-router-dom';

// ...and wherever the link goes...
<Link
  to={{
    pathname: paths.onboard,
    state: { flow: DAILY_CHECK_FLOW }
  }}
/>
// if it's not a link and it's an onClick / history.push type of situation, we can do history.push(path, state)!
```

**on the onboard, confirm, possibly critical questions, alert, symptoms & daily mesurements views** (i think those are all the ones involved in these two flows? bear in mind code will be different in each case)
- [useLocation](https://reactrouter.com/web/api/Hooks/uselocation) is a react router hook that allows you to get the location, which is the parent object that has the router state
- check also [this doc](https://reactrouter.com/web/api/history) to undestand how we're adding the state to the history push
```javascript
let location = useLocation(); // this can be fetched on a component-wide level!

// ...
if (selected === sicknessStatus.SICK) history.push(paths.alert);
    else history.push(paths.getNextPath(
       paths.onboard,
       // I'm using onboard here as an example, but this should be the path to the current component,
      // so, if you're in "confirm" this should be paths.confirm
     location
    ), {...location.state});
```

Whew, that was a long one! I hope I was clear, but please let me know if there's anything that I can do to further explain the suggestion 😄

**Comment by yxlin118** [comment]
@pyritewolf I used another state to keep track of whether onboard is done or not ( so only is undone if coming from /home but if coming from daily assessment, it would be set to done). I am wondering if this is an okay solution. Thank you so much! I appreciate your feedback and suggestions!

**Comment by yxlin118** [comment]
I didn't use link because confirm is the onclick situation and I was not able to figure out how to set up the link to set the state from dashboard and pass that to confirm. I am not sure if using states to store that information would be less efficient?

**Comment by pyritewolf** [comment]
This approach totally looks like it would work, just like the first approach worked, and we're no longer duplicating code so 🎉 hooray this is already awesome!

_However,_ (😅) using the Redux store for information that is not _data_ (such as this flag, which is a sort of flag or state the app can have) can quickly get out of hand in my experience. And `react-router`'s state is precisely meant for this sort of uses - passing along information from one view to the next regarding where to go next, or where to go back. Having this sort of logic encapsulated there would, I believe, help make sure it doesn't seep through and gets mixed up with taxonomically different stuff such as the user's data, story data, etc.

Stepping out from my nerdy React musings and going to the concrete questions!

> I am wondering if this is an okay solution.

It is! Although... a dangerous one for future devs who have to make sense of the redux store 😅 

> Thank you so much!

Thank _you_ for contributing to the repo! 🖤 

> I didn't use link because confirm is the onclick situation and I was not able to figure out how to set up the link to set the state from dashboard and pass that to confirm.

Sorry I didn't leave a more complete example for that case, I was rather hoping it wasn't implemented that way 😛 I just saw how it's done, and the full array of tweaks on `<Dashboard />` would be something like...

```javascript
const actions = [
  { name: "ADD MY STORY", href: paths.myStory, classes: "MuiFab-extended" },
  {
    name: "DAILY ASSESSMENT",
    href: paths.onboard,
    state: { flow: DAILY_CHECK_FLOW }
    classes: classNames("MuiFab-extended assessment", styles.assessment),
  },
];

// ...some wonderful wonderful code...

const handleClick = (path, state) => () => {
    props.history.push(path, state);
};

// ...blah blah...

{actions.map((action) => (
    <SpeedDialAction
       key={action.name}
       icon={action.name}
       tooltipTitle={action.name}
       className={action.classes}
       onClick={handleClick(action.href, action.state || {})} // we add a default just in case the action has no state 😉 
     ></SpeedDialAction>
))}
```

> I am not sure if using states to store that information would be less efficient?

Efficiency in React is a tricky issue. As a rule of thumb, modifying the redux store is an inefficient action because redux doesn't just modify that key and that's it, it regenerates the entire store every time there's a change. This will also trigger re-renders on components consuming slices of that store. As useful as it is a tool, it can get out of hand pretty quickly... thus my conservative approach to it, trying to bound its use to merely data handling and minor API state statuses 😊 

Like I mentioned before, I'm sure this code works just fine and please feel free to merge it if you feel comfortable with it! If, on the other hand, you want to follow my suggestions, remember I'm here if you have any further questions or ideas on how to approach the problem 🙇

**Comment by yxlin118** [comment]
@pyritewolf  Thanks for all your wonderful feedback! I learned so much:) So for this version, I used location and history's state to keep track of whether onboard is done or not. I only wrote a helper function to decide flows after /confirm. Thank you so much again!!

**Pull request merged**
