### PR TITLE
Replace ethnicity, current location and postal code

### PR DESCRIPTION
**Pull request by ste519**

### CODE REVIEW

**Comment by ste519** [comment]
I tried to place the fields "ethnicity" with "city" and "current location" with "country", but I couldn't really figure out what causes the checks to fail. Can I ask you for help with this? @pyritewolf

**Comment by pyritewolf** [comment]
Hey @ste519 ! It's nice to see you around! 😄 

The issue is you changed the backend logic, but the database hasn't realized there's changes yet. Essentially - the backend is trying to access the tables as if those new fields were there, but the database still thinks "currentLocation" is a thing!

You need to explicitly notify the database of the changes by generating (and running in your computer) **migrations** that will update the database tables to the changes in the backend. Fortunately Python makes it super easy! Check out the instructions in [this section of the readme doc](https://github.com/instedd/oasis#generating--running-migrations) and let me know if something doesn't work.

**Comment by pyritewolf** [comment]
Heya! Just a quick update. The code looks great, but I haven't been able to see it working locally due to an unrelated bug that Ana is working on (#134). As soon as that's solved I'll test this on my computer and give the thumbs up if nothing comes up!

On an unrelated note, I'm adding this PR to the [Github Project](https://github.com/instedd/oasis/projects/1) for tracking purposes - our QA, Mauri, is testing everything once it's merged to master in our [staging environment](http://oasis-stg.instedd.org/). If he finds any problems, he'll add an issue to the backlog 😄

**Comment by ste519** [comment]
Totally agreed. I‘ll definitely keep that in mind when we start to redesign the interface, thanks!

**Pull request merged**
